### PR TITLE
Multi accounts

### LINKED ISSUE #23: [Feature Request] UserConfig.MAX_ACCOUNT_COUNT from 32 to infinity.
I don't think it's too difficult to implement. Why having a client-side limit?

### PR DESCRIPTION
**Pull request by ArmeF97**
maybe fix #23

### CODE REVIEW

**Comment by ArmeF97** [comment]
Wait, I found a bug, It seems that other accounts are hidden, except for first, I need to find the if/else that causes this and fix

**Comment by ArmeF97** [comment]
it seems fixed, now we can increase the number just as it were an int

**Comment by rikakomoe** [comment]
@ArmeF97 Have you tested adding more than 32 accounts?

**Comment by rikakomoe** [comment]
I suppose, although I didn't test by myself, the application will crash (or have other severe issue) when trying to log in the 33th account, since you didn't change this

https://github.com/Nekogram/Nekogram/blob/fa317c6de916fb05b39dca1c6f8fa60806ed251b/TMessagesProj/jni/tgnet/ConnectionsManager.cpp#L131-L231

I tried to change ConnectionsManager::getInstance to

```cpp
ConnectionsManager& ConnectionsManager::getInstance(int32_t instanceNum) {
    static std::map<int32_t, ConnectionsManager*> instanceMap;
    if (instanceMap.find(instanceNum) == instanceMap.end()) {
        ConnectionsManager* instance = new ConnectionsManager(instanceNum);
        instanceMap[instanceNum] = std::move(instance);
    }
    return *instanceMap[instanceNum];
}
```

But app will crash when application launches. As I debug into this issue, the segmentation fault were thrown from

https://github.com/Nekogram/Nekogram/blob/fa317c6de916fb05b39dca1c6f8fa60806ed251b/TMessagesProj/jni/tgnet/ConnectionsManager.cpp#L3449-L3453

I guess it might be a thread-safety issue, since std::map is not thread-safe. We need further investigation.

**Comment by NekoInverter** [comment]
Closed due to inactivity

**Pull request closed without merging**
